### ISSUE TITLE
KeyError:"num_envs"

### ISSUE THREAD

**Issue by Q5mi1e** [georgao35/ReST#1]
Thank you for impressive research.
I want to reproduce your result .
However, when I follow your training half cheetah example,

`python main.py --env HalfCheetah --expname halfcheetah --epochs 50 --num_skills 10`

i got a following error:
```
/home/admin641/anaconda3/envs/qs_ReST/lib/python3.8/site-packages/gym/envs/registration.py:498: UserWarning: WARN: Overriding environment Humanoid-v4 already in registry.
  logger.warn(f"Overriding environment {new_spec.id} already in registry.")
/home/admin641/anaconda3/envs/qs_ReST/lib/python3.8/site-packages/gym/envs/registration.py:498: UserWarning: WARN: Overriding environment Ant-v4 already in registry.
  logger.warn(f"Overriding environment {new_spec.id} already in registry.")
/home/admin641/anaconda3/envs/qs_ReST/lib/python3.8/site-packages/gym/envs/registration.py:498: UserWarning: WARN: Overriding environment HalfCheetah-v4 already in registry.
  logger.warn(f"Overriding environment {new_spec.id} already in registry.")
Logging data to ./data/HalfCheetah/2023-05-23T15-25-28/halfcheetah/halfcheetah_s0/progress.txt
Saving config:

{
    "algo":     "PPO",
    "data_dir": "./data/HalfCheetah/2023-05-23T15-25-28/",
    "env_name": "HalfCheetah",
    "epochs":   50,
    "exp_name": "halfcheetah",
    "expname":  "halfcheetah",
    "logger":   {
        "<simulator_utils.logx.EpochLogger object at 0x7fb8f15dabe0>":  {
            "epoch_dict":       {},
            "exp_name": "halfcheetah",
            "first_row":        true,
            "log_current_row":  {},
            "log_headers":      [],
            "output_dir":       "./data/HalfCheetah/2023-05-23T15-25-28/halfcheetah/halfcheetah_s0",
            "output_file":      {
                "<_io.TextIOWrapper name='./data/HalfCheetah/2023-05-23T15-25-28/halfcheetah/halfcheetah_s0/progress.txt' mode='w' encoding='UTF-8'>":  {
                    "mode":     "w"
                }
            }
        }
    },
    "logger_kwargs":    {
        "exp_name":     "halfcheetah",
        "output_dir":   "./data/HalfCheetah/2023-05-23T15-25-28/halfcheetah/halfcheetah_s0"
    },
    "num_skills":       10,
    "save_dir": "./data/"
}
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    train(env_name=args.env,
  File "main.py", line 26, in train
    simulator = Simulator(config[env_name], expname)
  File "/home/admin641/qs/ReST-main/simulator_utils/simulator.py", line 16, in __init__
    self.num_envs = config['num_envs']
KeyError: 'num_envs'
```

**Comment by Q5mi1e** [comment]
Hi.
First of all,thank you for publishing the ReST code.
my python version is 3.8.16
When i run the command   python main.py --env HalfCheetah --expname halfcheetah --epochs 50 --num_skills 10

i got this error:
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    train(env_name=args.env,
  File "main.py", line 26, in train
    simulator = Simulator(config[env_name], expname)
  File "/home/admin641/qs/ReST-main/simulator_utils/simulator.py", line 16, in __init__
    self.num_envs = config['num_envs']
KeyError: 'num_envs'
